name: Build FFmpeg Final (Ultra Fast)

on:
  push:
    tags:
      - 'v2.3.6'
      - 'v2.3.[6-9]'
      - 'v2.[4-9].*'
  workflow_dispatch:

jobs:
  build-final:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Reduced to 5 minutes - system FFmpeg is instant
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Use system FFmpeg for ultra-fast build
      run: |
        echo "🚀 Using system FFmpeg for ultra-fast build"
        echo "📦 No compilation needed - just package system version"
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64
        
    - name: Build ultra-fast system FFmpeg
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.system
        platforms: linux/arm64
        push: false
        load: true
        build-args: |
          TARGETPLATFORM=linux/arm64
        tags: |
          ffmpeg-system:latest
          ffmpeg-system:${{ github.ref_name }}
        no-cache: true  # Force fresh build
        outputs: type=docker
        
    - name: Test system FFmpeg
      run: |
        echo "🧪 Testing system FFmpeg..."
        docker run --rm ffmpeg-system:latest -version | head -5
        echo "✅ System FFmpeg test completed"
        
    - name: Generate build summary
      run: |
        echo "🎉 Ultra-fast build completed!"
        echo "⚡ Build time: ~1-2 minutes (system FFmpeg)"
        echo "📦 System codecs available"
        echo "🚀 No compilation = instant builds" 