name: Build FFmpeg for Apple Silicon

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Reduced to 30 minutes for fast build
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64
        
    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/arm64
        push: false
        load: true
        build-args: |
          TARGETPLATFORM=linux/arm64
        tags: |
          ffmpeg-apple-silicon:latest
          ffmpeg-apple-silicon:${{ github.ref_name }}
        no-cache: true
        outputs: type=docker
        
    - name: Test FFmpeg binary
      run: |
        echo "🧪 Testing FFmpeg binary..."
        docker run --rm ffmpeg-apple-silicon:latest -version
        echo "✅ FFmpeg binary test completed"
        
    - name: Generate build report
      run: |
        echo "📊 Build Report for ${{ github.ref_name }}"
        echo "- Build completed successfully"
        echo "- Platform: linux/arm64" 
        echo "- Codecs: Built-in H.264, AAC, MP3 decoders only"
        echo "- Build time: ~1-2 minutes (ultra-minimal)"
        docker run --rm ffmpeg-apple-silicon:latest -version | grep "built with" 